2017-11-27 20:02:11,419:INFO:request course list for dashboard
2017-11-27 20:02:14,590:INFO:request course detail success: course code = COMP3335
2017-11-27 20:05:50,159:ERROR:Internal Server Error: /account/register
Traceback (most recent call last):
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.DataError: (1406, "Data too long for column 'age' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xiating/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/xiating/dbsec/comp3335_project/comp3335/account/views.py", line 32, in register
    acct.save()
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/xiating/.local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/xiating/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'age' at row 1")
2017-11-27 20:26:38,047:INFO:request course list for dashboard
2017-11-27 20:31:35,665:INFO:request course list for dashboard
2017-11-27 20:33:34,911:INFO:request course list for dashboard
2017-11-27 20:33:51,351:INFO:request course list for dashboard
2017-11-27 20:33:58,433:INFO:request course list for dashboard
2017-11-27 20:34:02,945:INFO:request course list for dashboard
2017-11-27 20:38:06,836:INFO:request course detail success: course code = COMP3335
2017-11-27 20:38:21,516:INFO:request course detail success: course code = COMP4431
2017-11-27 20:38:35,902:INFO:insert message: course code = COMP4431, message = 
2017-11-27 20:38:37,144:INFO:insert message: course code = COMP4431, message = 
2017-11-27 20:38:37,425:INFO:insert message: course code = COMP4431, message = 
2017-11-27 20:38:37,706:INFO:insert message: course code = COMP4431, message = 
2017-11-27 20:38:39,457:INFO:insert message: course code = COMP4431, message = sdas
2017-11-27 20:38:40,975:INFO:insert message: course code = COMP4431, message = dsafsd
2017-11-27 20:38:42,062:INFO:insert message: course code = COMP4431, message = 
2017-11-27 20:38:44,458:INFO:insert message: course code = COMP4431, message = ssss
2017-11-27 20:38:55,103:INFO:request course list for dashboard
2017-11-27 20:38:57,194:INFO:request course detail success: course code = COMP3335
2017-11-27 20:39:02,478:INFO:insert message: course code = COMP3335, message = this is shit
2017-11-27 20:39:09,084:INFO:insert message: course code = COMP3335, message = send
2017-11-27 20:39:09,904:INFO:insert message: course code = COMP3335, message = send
